// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmitVFP9clYnyRr_J0R6eciKZZVBrT180',
    appId: '1:320153364438:web:0583ad781b29ca4f79a677',
    messagingSenderId: '320153364438',
    projectId: 'outsource-dev2026-487420',
    authDomain: 'outsource-dev2026-487420.firebaseapp.com',
    storageBucket: 'outsource-dev2026-487420.firebasestorage.app',
    measurementId: 'G-LL8EQMFWGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeidcyDbeSYKdoi9a8wsbv80ccrNlxlQg',
    appId: '1:320153364438:android:f3ca5f885b8dae8979a677',
    messagingSenderId: '320153364438',
    projectId: 'outsource-dev2026-487420',
    storageBucket: 'outsource-dev2026-487420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorb16w5DEZ1cmx9kej49MC0OsnzB6Q-k',
    appId: '1:320153364438:ios:c44c88f7007ea83579a677',
    messagingSenderId: '320153364438',
    projectId: 'outsource-dev2026-487420',
    storageBucket: 'outsource-dev2026-487420.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorb16w5DEZ1cmx9kej49MC0OsnzB6Q-k',
    appId: '1:320153364438:ios:c44c88f7007ea83579a677',
    messagingSenderId: '320153364438',
    projectId: 'outsource-dev2026-487420',
    storageBucket: 'outsource-dev2026-487420.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmitVFP9clYnyRr_J0R6eciKZZVBrT180',
    appId: '1:320153364438:web:86ed9cbd14a175c079a677',
    messagingSenderId: '320153364438',
    projectId: 'outsource-dev2026-487420',
    authDomain: 'outsource-dev2026-487420.firebaseapp.com',
    storageBucket: 'outsource-dev2026-487420.firebasestorage.app',
    measurementId: 'G-BC38R70KXX',
  );
}
